### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wjxshen** [IvanBuccella/CamAlert#1]
Hello, I want to do a project using Raspberry PI to upload the temperature and humidity collected by DBT11 sensor to nuclio and then store the data in rabbitmq. The project I want to complete has a lot in common with yours. Because it is the first time for me to contact nuclio, I can't do many things. You can help me finish it or you can finish it for me, I can pay the money, if you can, please reply me thank you, and give me your contact information

**Comment by IvanBuccella** [comment]
Hi, you can write me an email at ivan@buccella.dev where you should provide more details and I'll try to help you.
